services:
  - type: web
    name: health-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn healthapi.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: health_db
          property: connectionString
    autoDeploy: true
    plan: free
    preDeployCommand: python manage.py migrate
