# Generated by Django 5.1.6 on 2025-04-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='content',
            new_name='text',
        ),
    ]
