# Generated by Django 5.1.6 on 2025-04-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_content_tip_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='text',
            new_name='content',
        ),
    ]
