# Generated by Django 5.1.6 on 2025-05-10 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activitylog_steplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='portion_large',
            field=models.FloatField(blank=True, default=150, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='portion_medium',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='portion_small',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
