# Generated by Django 5.1.6 on 2025-06-09 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_food_portion_large_alter_food_portion_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
