# Generated by Django 5.1.6 on 2025-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_waterlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_daily_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
