# Generated by Django 5.1.6 on 2025-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_target_daily_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_daily_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
